version: '3'

services:
  latelier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - mongo
    environment:
      LATELIER_VERSION: v2.9.0
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      MAIL_URL: smtp://maildev:25
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      METEOR_SETTINGS: '{
        "generateFixtures": false,
        "disableAccountCreation": false,
        "attachmentsPath": "/attachments",
        "email": {
          "from": "noreply@latelierdesprojets.fr",
          "prefix": "[latelier]"
        },
        "roles": {
          "admin": ["admin@latelierdesprojets.fr"]
        }
      }'
    volumes:
        - ./attachments:/attachments
  
  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"

volumes:
  data: